services:
  postgres:
    image: postgres:16
    container_name: crm-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: base_user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: devdb
    ports:
      - "5433:5432"
    volumes:
      - crm_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U base_user -d devdb"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  crm_postgres_data: