api:
  dashboard: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: cloudflare
        domains:
          - main: stanciulescu.xyz
            sans:
              - "*.stanciulescu.xyz"

providers:
  docker:
    exposedByDefault: false
    network: moduvis-web

certificatesResolvers:
  cloudflare:
    acme:
      email: admin@stanciulescu.xyz
      storage: /letsencrypt/acme.json
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 0

log:
  level: INFO

accessLog: {}
